version: "3"

services:
  mysql:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbuser
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "dbuser",
          "-ppassword",
        ]
      interval: 5s
      timeout: 20s
      retries: 5
  proxy:
    build: .
    restart: always
    environment:
      PROXY_DB_PORT: 3306
      REMOTE_DB_HOST: mysql
      REMOTE_DB_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
